---
- name: A simple play to test ansible.cfg
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:

  - name: using apt to remove cowsay        # metadata
    ansible.builtin.apt:                     # the module we want to run, apt.py
        name: cowsay                         # parameter name has the value figlet
        state: absent      # parameter state has the value present
    become: yes 

  # the command module issues a command on the remote host
  - name: Issue a date cmd on each remote host
    command: date

