---
 - name: Playbook with the register keyword
   hosts: planetexpress
   connection: ansible.builtin.ssh

   tasks:

     - name: "Issue a trivial command"
       ansible.builtin.command: ls /lib/
       register: contentz_lib

     - name: "debug - display data returned"
       ansible.builtin.debug:                  # display to stdout
         msg: "{{ contentz_lib }}"

     - name: "debug - standard error"         #handle when there is no /lib/ available
       ansible.builtin.debug:
         msg: "{{ contentz_lib.stderr }}"

     - name: "debug - standard out"
       ansible.builtin.debug:
         msg: "{{ contentz_lib.stdout }}"

     - name: "debug - standard out as list"  #display as list of items in /lib/
       ansible.builtin.debug:
         msg: "{{ contentz_lib.stdout_lines }}"
