# use the arista backup role we created in galaxy/roles/arista_backup
# besure to include the following in .ansible.cfg:
# roles_path=~/galaxy/roles/

---
- name: Using the arista_backup role we created
  hosts: all
  connection: network_cli   # used to  connect to network devices
  gather_facts: yes

  vars:
    ansible_network_os: eos

  vars_files:
    - ~/switch.creds

  roles:
    - arista_backup

  tasks:
    - name: print to the screen
      debug:
        msg: "the roles section will run before any tasks"

