---
- name: change switch configuration
  hosts: eosswitches:iosswitches   # these two groups
  gather_facts: false
  become: yes # run the entire playbook as enable
  connection: network_cli # required mode

  tasks:

    - name: load new NTP configuration
      cli_config:
        config: "{{ntp_commands}}"   # "ntp_commands" defined in /group_vars/
      notify:
        - save and commit  ## after running "ntp_commands", notify the "save and commit" handler below

  handlers:
    # handlers only run if a task runs that
    # notifies the handler to run
    - name: save and commit  # this name matches the notify
      cli_command:
        command: "{{save}}"     # "save" defined in /group_vars/ but notice the different for EOS and ios

