- name: My Arista Playbook
  hosts: switches
  gather_facts: false

  vars_files:
    - ~/switch.creds   #use the login info in switch.creds to login instead of defind in the playbook

  tasks:
  - name: configure the login banner
    eos_banner:
      banner: login
      text: |
        Congrats! You set a banner using an Ansible EOS module.
        Notice how YAML formatting lets us do multi-line
        strings
      state: "{{ herethere }}"    ## this allow us to pass in the state (present or absent) during playbook excecution.


        ### Usage: ansible-playbook ~/mycode/playbook-netswitch02.yml -i ~/mycode/inv/dev/hosts -e herethere=absent
