- name: Use Redfish to gather CPU Inventory, and Virtual Media Information
  hosts: localhost   # this is the localhost or can be a group of hosts we are using
  connection: local   # we don't want to SSH anywhere
  gather_facts: false  # if we did gather facts, they would be about ourselves (connection:local)
  
  vars:
    baseuri: 10.0.0.89
    username: root
    password: r0gerwilc0

  collections:
    community.general

  tasks:
  - name: Get CPU Inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: cpuInv

  - name: Display CPU data
    debug:
      var: cpuInv

  - name: Get Virtual Media Information
    community.general.redfish_info:
      category: Manager
      command: GetVirtualMedia
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: mediaInformation

  - name: Display virtual media information
    debug:
      var: mediaInformation.redfish_facts.virtual_media.entries

