## Usage:
#1.ansible-playbook ~/mycode/template-playbook02.yml
#
#2. Variables can always be defined at the command line when a playbook run is invoked.
#Run the playbook again, but define the variable planet as luna park. As CLI variables have the highest precedence,
#the playbook executor always has final control of the way variables are defined.
# command:  ansible-playbook ~/mycode/template-playbook02.yml -e "planet='luna park'"
---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts
  connection: ansible.builtin.ssh   # default connection type

  # these variables are used to build templates
  vars_files:
    - vars/planetexpress.yml

  tasks:
    - name: Configure spaceship registration
      ansible.builtin.template:
        src: templates/ship.cfg.j2    # name of the template on ansible controller
        dest: ~/ship.cfg              # name of the completed file to be placed on the target system

    - name: Configure mission orders
      ansible.builtin.template:
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: ~/mission-orders.txt              # name of the completed file to be placed on the target system

