---
- name: Get-URL Download the Protected File
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "url_username"
      prompt: "Enter the username for the URL"
      private: no

    - name: "url_password"
      prompt: "Enter the password for the URL"
      private: yes

  tasks:
    - name: Access the Website and make sure the URL is live
      ansible.builtin.uri:
        method: GET
        url: http://10.10.2.4/admin/secure.txt
        status_code: 401
        return_content: true
      register: validateurl

    - name: "INFO: HTTP Response for the URL"
      ansible.builtin.debug:
        var: validateurl.msg

    - name: Access the same URL with Basic Authentication and Download the file
      ansible.builtin.uri:
        method: GET
        url: http://10.10.2.4/admin/secure.txt
        status_code: 200
        return_content: yes
        url_username: "{{ url_username }}"
        url_password: "{{ url_password }}"
      register: validateurl

    - name: Print out the content of the file "secure.txt"
      ansible.builtin.debug:
        var: validateurl.content

    - name: Put secret content of the "secure.txt" into the txt file
      ansible.builtin.copy:
        content: "{{ validateurl.content }}"
        dest: ~/ansible-downloaded-the-secret-file.txt

